#! /usr/bin/dh-exec
usr/include/*
usr/lib/*/pkgconfig/*
usr/share/pcl*/*.cmake usr/lib/${DEB_HOST_MULTIARCH}/cmake/pcl/
usr/lib/*/libpcl_common.so
usr/lib/*/libpcl_features.so
usr/lib/*/libpcl_filters.so
usr/lib/*/libpcl_io.so
usr/lib/*/libpcl_io_ply.so
usr/lib/*/libpcl_kdtree.so
usr/lib/*/libpcl_keypoints.so
usr/lib/*/libpcl_octree.so
usr/lib/*/libpcl_outofcore.so
usr/lib/*/libpcl_people.so
usr/lib/*/libpcl_recognition.so
usr/lib/*/libpcl_registration.so
usr/lib/*/libpcl_sample_consensus.so
usr/lib/*/libpcl_search.so
usr/lib/*/libpcl_segmentation.so
usr/lib/*/libpcl_surface.so
usr/lib/*/libpcl_tracking.so
usr/lib/*/libpcl_visualization.so
